name: Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        couchdb: ["3.3", "3.2", "3.1", "2.3"]
    steps:
    - uses: actions/checkout@v1
    - name: Set up CouchDB
      uses: ./
      with:
        couchdb version: ${{ matrix.couchdb }}
      env:
        COUCHDB_USERNAME: admin
        COUCHDB_PASSOWRD: password
    - name: Test that CouchDB can be accessed
      run: curl -sS -f http://admin:password@127.0.0.1:5984/
    - name: Test that system databases are there
      run: curl -sS -f http://admin:password@127.0.0.1:5984/_users
    - name: Test that the Erlang query server is enabled
      run: |
        curl -sS -f 'http://admin:password@127.0.0.1:5984/_users/_design/test' -X PUT -H 'Content-Type: application/json' --data '{"views":{"test":{"map":"fun({Doc}) -> Emit(proplists:get_value(<<\"name\">>, Doc, null), 1) end."}},"language":"erlang"}'
        curl -sS -f 'http://admin:password@127.0.0.1:5984/_users/_design/test/_view/test'
